In [11]:
import pandas as pd
import glob

Consolidating Fundamentals

In [12]:
symbols = ['GOOGL', 'META', 'MSFT', 'NVDA', 'PLTR']

In [13]:
all_files = []
for symbol in symbols:

    csv_files = glob.glob(f'/workspaces/bubbleindex/bronze/{symbol}/*.csv')
    all_files.append(csv_files)

In [14]:
print(all_files)

[['/workspaces/bubbleindex/bronze/GOOGL/GOOGL_price.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv'], ['/workspaces/bubbleindex/bronze/META/META_price.csv', '/workspaces/bubbleindex/bronze/META/META_balancesheet.csv', '/workspaces/bubbleindex/bronze/META/META_incomestatement.csv', '/workspaces/bubbleindex/bronze/META/META_cashflow.csv'], ['/workspaces/bubbleindex/bronze/MSFT/MSFT_price.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_balancesheet.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_cashflow.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_incomestatement.csv'], ['/workspaces/bubbleindex/bronze/NVDA/NVDA_price.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_cashflow.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_balancesheet.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_incomestatement.csv'], ['/workspaces/bubbleindex/bronze/PLTR/PLTR_cashflow.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_incomestatement.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_price.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_balancesheet.csv']]

In [ ]:

#list of fundamentals for each company (googldf, metadf, pltrdf2,etc)
final_fundamentals_dfs = []
#symbol = ['/workspaces/bubbleindex/bronze/GOOGL/GOOGL_price.csv', 
#           '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', 
#       # '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', 
#       '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv']
for symbol in all_files:
    #list of all fundamentals dfs (df,df1,df2)
    fundamentals_files = []
    #csvfile = '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_price.csv
    for csv_file in symbol:
        #if csv_file is a price file skip it
        if not csv_file.endswith('_price.csv'):
            df = pd.read_csv(csv_file)
            df = df.rename(columns={'Unnamed: 0': 'Date'}) 

            #filter columns based on file type
            if csv_file.endswith('_balancesheet.csv'):
                df = df[['ticker', 'Date', 'Total Debt', 'Working Capital']]
            elif csv_file.endswith('_cashflow.csv'):
                df = df[['ticker', 'Date', 'Free Cash Flow', 'Beginning Cash Position' , 'End Cash Position', 'Cash Dividends Paid']]
            else:
                df = df[['ticker', 'Date', 'Total Revenue', 'Gross Profit', 'Net Income', 'Diluted EPS', 'Research And Development', 'EBITDA', 'Tax Provision']]
            fundamentals_files.append(df)
    
            fundamentals_df = fundamentals_files[0].merge(fundamentals_files[1], on=['ticker', 'Date'], how='inner').merge(fundamentals_files[2], on=['ticker', 'Date'], how='inner')
            fundamentals_df.to_csv(f'/workspaces/bubbleindex/silver/{symbol}_fundamentals.csv', index=False)
    final_fundamentals_dfs.append(fundamentals_df)


# combine all fundamentals dfs into one
combined_fundamentals = pd.concat([final_fundamentals_dfs[0], final_fundamentals_dfs[1], final_fundamentals_dfs[2]], ignore_index=True)
combined_fundamentals.to_csv('/workspaces/bubbleindex/silver/combined_fundamentals.csv', index=False)

OSError: Cannot save file into a non-existent directory: '/workspaces/bubbleindex/silver/['/workspaces/bubbleindex/bronze/GOOGL/GOOGL_price.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL'

In [ ]:

# drop all “price” csvs from the list
csv_files = [f for f in csv_files if not f.endswith('_price.csv')]
print(csv_files)

['/workspaces/bubbleindex/bronze/META/META_balancesheet.csv', '/workspaces/bubbleindex/bronze/META/META_incomestatement.csv', '/workspaces/bubbleindex/bronze/META/META_cashflow.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_cashflow.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_incomestatement.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_balancesheet.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_balancesheet.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_cashflow.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_incomestatement.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_cashflow.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_balancesheet.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv']

GOOGL fundamentals

In [20]:
df = pd.read_csv(r'/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv')

In [21]:
df

,Unnamed: 0,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,...,Inventory,Receivables,Taxes Receivable,Accounts Receivable,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,ticker
0,2025-12-31,NaN,1.208800e+10,1.208800e+10,1.583900e+10,5.929100e+10,3.818850e+11,4.618120e+11,1.032930e+11,3.818850e+11,...,NaN,6.288600e+10,NaN,6.288600e+10,-924000000.0,6.381000e+10,1.268430e+11,9.613500e+10,3.070800e+10,GOOGL
1,2024-12-31,NaN,1.221100e+10,1.221100e+10,NaN,2.257400e+10,2.931990e+11,3.359670e+11,7.458900e+10,2.931990e+11,...,NaN,5.234000e+10,NaN,5.234000e+10,-879000000.0,5.321900e+10,9.565700e+10,7.219100e+10,2.346600e+10,GOOGL
2,2023-12-31,0.0,1.246000e+10,1.246000e+10,NaN,2.712100e+10,2.541810e+11,2.952490e+11,8.971600e+10,2.541810e+11,...,NaN,4.796400e+10,NaN,4.796400e+10,-771000000.0,4.873500e+10,1.109160e+11,8.686800e+10,2.404800e+10,GOOGL
3,2022-12-31,NaN,1.284900e+10,1.284900e+10,NaN,2.967900e+10,2.271840e+11,2.690010e+11,9.549500e+10,2.271840e+11,...,2.670000e+09,4.025800e+10,NaN,4.025800e+10,-754000000.0,4.101200e+10,1.137620e+11,9.188300e+10,2.187900e+10,GOOGL
4,2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.170000e+09,NaN,966000000.0,NaN,NaN,NaN,NaN,NaN,NaN,GOOGL

In [22]:
df = df.rename(columns={'Unnamed: 0': 'Date'})

In [23]:
df = df[['ticker', 'Date', 'Total Debt', 'Working Capital']]

In [24]:
df

  ticker        Date    Total Debt  Working Capital
0  GOOGL  2025-12-31  5.929100e+10     1.032930e+11
1  GOOGL  2024-12-31  2.257400e+10     7.458900e+10
2  GOOGL  2023-12-31  2.712100e+10     8.971600e+10
3  GOOGL  2022-12-31  2.967900e+10     9.549500e+10
4  GOOGL  2021-12-31           NaN              NaN

In [25]:
df.columns

Index(['ticker', 'Date', 'Total Debt', 'Working Capital'], dtype='str')

In [26]:
df1 = pd.read_csv(r'/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv')

In [27]:
df1 = df1.rename(columns={'Unnamed: 0': 'Date'})

In [28]:
df1.columns

Index(['Date', 'Free Cash Flow', 'Repurchase Of Capital Stock',
       'Repayment Of Debt', 'Issuance Of Debt', 'Capital Expenditure',
       'Income Tax Paid Supplemental Data', 'End Cash Position',
       'Beginning Cash Position', 'Effect Of Exchange Rate Changes',
       'Changes In Cash', 'Financing Cash Flow',
       'Cash Flow From Continuing Financing Activities',
       'Net Other Financing Charges', 'Proceeds From Stock Option Exercised',
       'Cash Dividends Paid', 'Common Stock Dividend Paid',
       'Net Common Stock Issuance', 'Common Stock Payments',
       'Net Issuance Payments Of Debt', 'Net Long Term Debt Issuance',
       'Long Term Debt Payments', 'Long Term Debt Issuance',
       'Investing Cash Flow', 'Cash Flow From Continuing Investing Activities',
       'Net Other Investing Changes', 'Net Investment Purchase And Sale',
       'Sale Of Investment', 'Purchase Of Investment',
       'Net Business Purchase And Sale', 'Purchase Of Business',
       'Net PPE Purchase And Sale', 'Purchase Of PPE', 'Operating Cash Flow',
       'Cash Flow From Continuing Operating Activities',
       'Change In Working Capital', 'Change In Other Working Capital',
       'Change In Other Current Assets',
       'Change In Payables And Accrued Expense', 'Change In Accrued Expense',
       'Change In Payable', 'Change In Account Payable',
       'Change In Receivables', 'Changes In Account Receivables',
       'Other Non Cash Items', 'Stock Based Compensation', 'Deferred Tax',
       'Deferred Income Tax', 'Depreciation Amortization Depletion',
       'Depreciation And Amortization', 'Amortization Cash Flow',
       'Amortization Of Intangibles', 'Depreciation', 'Operating Gains Losses',
       'Gain Loss On Investment Securities',
       'Net Income From Continuing Operations', 'ticker'],
      dtype='str')

In [32]:
df1 = df1[['ticker', 'Date', 'Free Cash Flow', 'Beginning Cash Position' , 'End Cash Position', 'Cash Dividends Paid']]

In [30]:
df1.columns

Index(['ticker', 'Date', 'Free Cash Flow', 'Beginning Cash Position',
       'End Cash Position', 'Cash Dividends Paid'],
      dtype='str')

In [33]:
df1.head()

,ticker,Date,Free Cash Flow,Beginning Cash Position,End Cash Position,Cash Dividends Paid
0,GOOGL,2025-12-31,7.326600e+10,2.346600e+10,3.070800e+10,-1.004900e+10
1,GOOGL,2024-12-31,7.276400e+10,2.404800e+10,2.346600e+10,-7.363000e+09
2,GOOGL,2023-12-31,6.949500e+10,2.187900e+10,2.404800e+10,0.000000e+00
3,GOOGL,2022-12-31,6.001000e+10,2.094500e+10,2.187900e+10,0.000000e+00
4,GOOGL,2021-12-31,NaN,NaN,NaN,NaN

In [34]:
df2 = pd.read_csv(r'/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv')

In [37]:
df2 = df2.rename(columns={'Unnamed: 0': 'Date'})

In [39]:
df2 = df2[['ticker', 'Date', 'Total Revenue', 'Gross Profit', 'Net Income', 'Diluted EPS', 'Research And Development', 'EBITDA', 'Tax Provision']]

In [38]:
df2.columns

Index(['Date', 'Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Total Operating Income As Reported',
       'Diluted Average Shares', 'Basic Average Shares', 'Diluted EPS',
       'Basic EPS', 'Diluted NI Availto Com Stockholders',
       'Net Income Common Stockholders', 'Net Income',
       'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Income Expense', 'Other Non Operating Income Expenses',
       'Special Income Charges', 'Write Off', 'Earnings From Equity Interest',
       'Gain On Sale Of Security', 'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Research And Development',
       'Selling General And Administration', 'Selling And Marketing Expense',
       'General And Administrative Expense', 'Other Gand A', 'Gross Profit',
       'Cost Of Revenue', 'Total Revenue', 'Operating Revenue', 'ticker'],
      dtype='str')

In [40]:
df2

,ticker,Date,Total Revenue,Gross Profit,Net Income,Diluted EPS,Research And Development,EBITDA,Tax Provision
0,GOOGL,2025-12-31,4.028360e+11,2.403010e+11,1.321700e+11,10.81,6.108700e+10,1.806980e+11,2.665600e+10
1,GOOGL,2024-12-31,3.500180e+11,2.037120e+11,1.001180e+11,8.04,4.932600e+10,1.353940e+11,1.969700e+10
2,GOOGL,2023-12-31,3.073940e+11,1.740620e+11,7.379500e+10,5.80,4.542700e+10,9.797100e+10,1.192200e+10
3,GOOGL,2022-12-31,2.828360e+11,1.566330e+11,5.997200e+10,4.56,3.950000e+10,8.516000e+10,1.135600e+10
4,GOOGL,2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
fundamentals_df = df.merge(df1, on=['ticker', 'Date'], how='inner').merge(df2, on=['ticker', 'Date'], how='inner')

In [58]:
print(fundamentals_df['ticker'].nunique())

1